services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "1234"
      POSTGRES_DB: Juthoor
    ports:
      - "5432:5432"
    volumes:
      - juthoor_db_data:/var/lib/postgresql/data

  api:
    build: .
    depends_on:
      - db
    env_file: .env
    environment:
      DATABASE_URL: postgresql://postgres:1234@db:5432/Juthoor
      UPLOAD_DIR: /srv/uploads
    ports:
      - "8000:8000"
    volumes:
      - juthoor_uploads:/srv/uploads

volumes:
  juthoor_db_data:
  juthoor_uploads:
