import fs from 'node:fs';
import { install, all, find, text, byClass, byTag, byText, tick, FEl } from './fakedom.js';
const PY = JSON.parse(fs.readFileSync(new URL('./fixtures/py.json', import.meta.url), 'utf8'));
let role = 'student';
const ok = (json, status = 200) => ({ ok: status < 400, status, text: async () => JSON.stringify(json) });
const users = {
  student: { user_id: 'S1', handle: '4821', email: 's@x.jo', full_name: 'ليان', role: 'student', plan: 'basic', plan_source: 'own', plan_expires_at: null, trial_days_left: null },
  teacher: { user_id: 'T1', handle: '7001', email: 't@x.jo', full_name: 'سارة', role: 'teacher', plan: 'school', plan_source: 'trial', plan_expires_at: null, trial_days_left: 13 },
};
const fetchMock = async (url) => {
  const p = url.split('?')[0];
  if (p === '/health') return ok({ status: 'ok', ai_tutor: 'offline_fallback', demo: true });
  if (p === '/auth/me') return role === 'none' ? ok({ detail: 'invalid_token' }, 401) : ok(users[role]);
  if (p === '/curriculum/map') return ok(PY.map);
  if (p === '/curriculum/skills') return ok(PY.skills);
  if (p.endsWith('/adaptive/tree')) return ok(PY.tree_full);
  if (p.endsWith('/adaptive/bootstrap')) return ok({ state: { current_skill: 'adding_integers', skills: [] }, wallet: { coins: 120, gems: 3 }, avatar: {}, avatar_svg: '<svg id="me"></svg>', drilldowns: [], drilldowns_hidden: 0, plan: { plan: 'basic', limits: { questions_per_day: 20 }, remaining: { questions: 18, tutor: 5 } } });
  if (p === '/community/summary') return ok({ unread_messages: 2, pending_requests: 1 });
  if (p === '/classrooms') return ok([]);
  if (p === '/payments/plans') return ok(PY.plans);
  return ok({ detail: 'no_mock' }, 404);
};
const { body } = install(fetchMock);
const app = new FEl('div'); const splash = new FEl('div'); splash.attrs.id = 'splash';
globalThis.__registerId('app', app); globalThis.__registerId('splash', splash); body.appendChild(app); body.appendChild(splash);
localStorage.setItem('juthoor.token', 'tok');
location.hash = '#/';
const results = []; let failures = 0;
const check = (n, c, x = '') => { results.push([c, n, x]); if (!c) failures += 1; };
const main = await import('../../app/static/js/main.js');
await tick(120);
check('splash dismissed', splash.classList.contains('done'));
check('student nav has 7 links', byClass(app, 'nav-link').length === 7);
check('mobile tabbar present', byClass(app, 'tabbar').length === 1);
check('home tree is first content', byClass(app, 'view-root')[0] && byClass(app, 'stage').length === 1);
check('community badge shows 3', text(app).includes('3'));
check('wallet pill', text(app).includes('120'));
check('route table: student /practice', !!main.matchRoute('/practice', 'student'));
check('route table: teacher blocked from /practice', main.matchRoute('/practice', 'teacher') === null);
check('route table: params', main.matchRoute('/report/abc', 'parent').params.id === 'abc' && main.matchRoute('/checkout/pro', 'student').params.plan === 'pro');
check('route table: / differs by role', main.matchRoute('/', 'teacher').route.view.name === 'teacherView' && main.matchRoute('/', 'parent').route.view.name === 'parentView' && main.matchRoute('/', 'student').route.view.name === 'homeView');
check('parseHash query', main.parseHash('#/plans?paid=1&x=2').query.paid === '1' && main.parseHash('').path === '/');
check('links per role', main.linksFor('teacher').length === 3 && main.linksFor('parent')[0][1] === 'أبنائي');
location.hash = '#/plans'; window.__fire('hashchange'); await tick(60);
check('navigates to plans', text(app).includes('قارن الباقات'));
check('active link highlighted', byClass(app, 'nav-link').filter((e) => e.classList.contains('on')).length === 1);
location.hash = '#/nope'; window.__fire('hashchange'); await tick(30);
check('unknown path redirects home', location.hash === '#/');
location.hash = '#/login'; window.__fire('hashchange'); await tick(30);
check('logged-in user bounced from login', location.hash === '#/');
const avatarBtn = byClass(app, 'menu-wrap')[0].childNodes[0];
avatarBtn.click();
check('account menu opens', byClass(app, 'menu').length === 1 && text(app).includes('تسجيل الخروج'));
byText(app, 'button', 'تسجيل الخروج')[0].click(); await tick(30);
check('logout goes to login', location.hash === '#/login' && byClass(app, 'nav').length === 0);
window.__fire('hashchange'); await tick(60);
check('login screen rendered after logout', byClass(app, 'auth').length === 1);
check('token cleared', localStorage.getItem('juthoor.token') === null);
for (const [c, n, x] of results) console.log(`${c ? 'PASS' : 'FAIL'}  ${n}${x ? ' -> ' + x : ''}`);
console.log(`\n${results.length - failures}/${results.length} main/router checks passed`);
process.exit(failures ? 1 : 0);
